keybindings:
    f2:           coverage
    f5:           showplanes
    f6:           cameranames
    f7:           axes
    f8:           centerdot
    f11:          cameraview
    left:         shiftcenter -30 0 0
    right:        shiftcenter 30 0 0
    down:         shiftcenter 0 -30 0
    up:           shiftcenter 0 30 0
    page down:    shiftcenter 0 0 -30
    page up:      shiftcenter 0 0 30
