keybindings:
    f2:           coverage
    f6:           name
    f7:           axes
    f8:           cdot
    f11:          camview
    left:         sc -30 0 0
    right:        sc 30 0 0
    down:         sc 0 -30 0
    up:           sc 0 30 0
    page down:    sc 0 0 -30
    page up:      sc 0 0 30
